(
 (stanzas
 (
(CPP PROLOGUE
   "
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <ostream>
#include <iostream>
#include <vector>

#include \"nicejson_intf.h\"
#include \"cppffi.h\"
")
  (TYPEDEF
  ((mltype (EXP int))
   (cpptype (ID size_t))
   (name size_t)))


   (FOREIGN
    ((ID std::string))
    nicejson_foo
    (((PRIM INT) n))
     "_res0 = nicejson::foo(n); ")

   (FOREIGN
    ((TYCON "std::tuple" ((ID std::string) (PRIM INT))))
    nicejson_bar
    (((ID std::string) s) ((PRIM INT) n))
     "_res0 = nicejson::bar(s, n); ")
   )
  )
 )
