(
 (stanzas
 (
(CPP PROLOGUE
   "
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <ostream>
#include <iostream>
#include <vector>

#include \"nicejson_intf.h\"
#include \"cppffi.h\"
")
  (TYPEDEF
  ((mltype (EXP int))
   (cpptype (ID size_t))
   (name size_t)))


   (FOREIGN
    ((ID std::string))
    nicejson_foo
    (((PRIM INT) n))
     "_res0 = ocaml::nicejson::foo(n); ")

   (FOREIGN
    ((TYCON "std::tuple" ((ID std::string) (PRIM INT))))
    nicejson_bar
    (((ID std::string) s) ((PRIM INT) n))
     "_res0 = ocaml::nicejson::bar(s, n); ")

   (FOREIGN
    ()
    prepend_typelib_directory
    (((ID std::string) s))
     "ocaml::nicejson::prepend_typelib_directory(s); ")

   (FOREIGN
    ((ID std::string))
    install_typelib
    (((ID std::string) key) ((ID std::string) serialized))
     "_res0 = ocaml::nicejson::install_typelib(key, serialized); ")

   (FOREIGN
    ((ID std::string))
    require_typelib
    (((ID std::string) key))
     "_res0 = ocaml::nicejson::require_typelib(key); ")
   )
  )
 )
